package com.bshhr.docgenerator.domain.system.model;

import com.alibaba.excel.annotation.ExcelProperty;
import lombok.Data;

@Data
public class ExcelData {

    @ExcelProperty(index = 0)
    public Object c1;
    @ExcelProperty(index = 1)
    public Object c2;
    @ExcelProperty(index = 2)
    public Object c3;
    @ExcelProperty(index = 3)
    public Object c4;
    @ExcelProperty(index = 4)
    public Object c5;
    @ExcelProperty(index = 5)
    public Object c6;
    @ExcelProperty(index = 6)
    public Object c7;
    @ExcelProperty(index = 7)
    public Object c8;
    @ExcelProperty(index = 8)
    public Object c9;
    @ExcelProperty(index = 9)
    public Object c10;
    @ExcelProperty(index = 10)
    public Object c11;
    @ExcelProperty(index = 11)
    public Object c12;
    @ExcelProperty(index = 12)
    public Object c13;
    @ExcelProperty(index = 13)
    public Object c14;
    @ExcelProperty(index = 14)
    public Object c15;
    @ExcelProperty(index = 15)
    public Object c16;
    @ExcelProperty(index = 16)
    public Object c17;
    @ExcelProperty(index = 17)
    public Object c18;
    @ExcelProperty(index = 18)
    public Object c19;
    @ExcelProperty(index = 19)
    public Object c20;
    @ExcelProperty(index = 20)
    public Object c21;
    @ExcelProperty(index = 21)
    public Object c22;
    @ExcelProperty(index = 22)
    public Object c23;
    @ExcelProperty(index = 23)
    public Object c24;
    @ExcelProperty(index = 24)
    public Object c25;
    @ExcelProperty(index = 25)
    public Object c26;
    @ExcelProperty(index = 26)
    public Object c27;
    @ExcelProperty(index = 27)
    public Object c28;
    @ExcelProperty(index = 28)
    public Object c29;
    @ExcelProperty(index = 29)
    public Object c30;
    @ExcelProperty(index = 30)
    public Object c31;
    @ExcelProperty(index = 31)
    public Object c32;
    @ExcelProperty(index = 32)
    public Object c33;
    @ExcelProperty(index = 33)
    public Object c34;
    @ExcelProperty(index = 34)
    public Object c35;
    @ExcelProperty(index = 35)
    public Object c36;
    @ExcelProperty(index = 36)
    public Object c37;
    @ExcelProperty(index = 37)
    public Object c38;
    @ExcelProperty(index = 38)
    public Object c39;
    @ExcelProperty(index = 39)
    public Object c40;
    @ExcelProperty(index = 40)
    public Object c41;
    @ExcelProperty(index = 41)
    public Object c42;
    @ExcelProperty(index = 42)
    public Object c43;
    @ExcelProperty(index = 43)
    public Object c44;
    @ExcelProperty(index = 44)
    public Object c45;
    @ExcelProperty(index = 45)
    public Object c46;
    @ExcelProperty(index = 46)
    public Object c47;
    @ExcelProperty(index = 47)
    public Object c48;
    @ExcelProperty(index = 48)
    public Object c49;
    @ExcelProperty(index = 49)
    public Object c50;
    @ExcelProperty(index = 50)
    public Object c51;
    @ExcelProperty(index = 51)
    public Object c52;
    @ExcelProperty(index = 52)
    public Object c53;
    @ExcelProperty(index = 53)
    public Object c54;
    @ExcelProperty(index = 54)
    public Object c55;
    @ExcelProperty(index = 55)
    public Object c56;
    @ExcelProperty(index = 56)
    public Object c57;
    @ExcelProperty(index = 57)
    public Object c58;
    @ExcelProperty(index = 58)
    public Object c59;
    @ExcelProperty(index = 59)
    public Object c60;
    @ExcelProperty(index = 60)
    public Object c61;
    @ExcelProperty(index = 61)
    public Object c62;
    @ExcelProperty(index = 62)
    public Object c63;
    @ExcelProperty(index = 63)
    public Object c64;
    @ExcelProperty(index = 64)
    public Object c65;
    @ExcelProperty(index = 65)
    public Object c66;
    @ExcelProperty(index = 66)
    public Object c67;
    @ExcelProperty(index = 67)
    public Object c68;
    @ExcelProperty(index = 68)
    public Object c69;
    @ExcelProperty(index = 69)
    public Object c70;
    @ExcelProperty(index = 70)
    public Object c71;
    @ExcelProperty(index = 71)
    public Object c72;
    @ExcelProperty(index = 72)
    public Object c73;
    @ExcelProperty(index = 73)
    public Object c74;
    @ExcelProperty(index = 74)
    public Object c75;
    @ExcelProperty(index = 75)
    public Object c76;
    @ExcelProperty(index = 76)
    public Object c77;
    @ExcelProperty(index = 77)
    public Object c78;
    @ExcelProperty(index = 78)
    public Object c79;
    @ExcelProperty(index = 79)
    public Object c80;
    @ExcelProperty(index = 80)
    public Object c81;
    @ExcelProperty(index = 81)
    public Object c82;
    @ExcelProperty(index = 82)
    public Object c83;
    @ExcelProperty(index = 83)
    public Object c84;
    @ExcelProperty(index = 84)
    public Object c85;
    @ExcelProperty(index = 85)
    public Object c86;
    @ExcelProperty(index = 86)
    public Object c87;
    @ExcelProperty(index = 87)
    public Object c88;
    @ExcelProperty(index = 88)
    public Object c89;
    @ExcelProperty(index = 89)
    public Object c90;
    @ExcelProperty(index = 90)
    public Object c91;
    @ExcelProperty(index = 91)
    public Object c92;
    @ExcelProperty(index = 92)
    public Object c93;
    @ExcelProperty(index = 93)
    public Object c94;
    @ExcelProperty(index = 94)
    public Object c95;
    @ExcelProperty(index = 95)
    public Object c96;
    @ExcelProperty(index = 96)
    public Object c97;
    @ExcelProperty(index = 97)
    public Object c98;
    @ExcelProperty(index = 98)
    public Object c99;
    @ExcelProperty(index = 99)
    public Object c100;
    @ExcelProperty(index = 100)
    public Object c101;
    @ExcelProperty(index = 101)
    public Object c102;
    @ExcelProperty(index = 102)
    public Object c103;
    @ExcelProperty(index = 103)
    public Object c104;
    @ExcelProperty(index = 104)
    public Object c105;
    @ExcelProperty(index = 105)
    public Object c106;
    @ExcelProperty(index = 106)
    public Object c107;
    @ExcelProperty(index = 107)
    public Object c108;
    @ExcelProperty(index = 108)
    public Object c109;
    @ExcelProperty(index = 109)
    public Object c110;
    @ExcelProperty(index = 110)
    public Object c111;
    @ExcelProperty(index = 111)
    public Object c112;
    @ExcelProperty(index = 112)
    public Object c113;
    @ExcelProperty(index = 113)
    public Object c114;
    @ExcelProperty(index = 114)
    public Object c115;
    @ExcelProperty(index = 115)
    public Object c116;
    @ExcelProperty(index = 116)
    public Object c117;
    @ExcelProperty(index = 117)
    public Object c118;
    @ExcelProperty(index = 118)
    public Object c119;
    @ExcelProperty(index = 119)
    public Object c120;
    @ExcelProperty(index = 120)
    public Object c121;
    @ExcelProperty(index = 121)
    public Object c122;
    @ExcelProperty(index = 122)
    public Object c123;
    @ExcelProperty(index = 123)
    public Object c124;
    @ExcelProperty(index = 124)
    public Object c125;
    @ExcelProperty(index = 125)
    public Object c126;

}
